name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Use the appropriate Java version
        distribution: 'temurin'

    - name: Grant execute permission for mvnw
      run: chmod +x ./Application-Backend/mvnw  # Adjust the path as necessary

    - name: Build backend
      working-directory: ./Application-Backend
      run: ./mvnw clean install

    - name: Run backend tests
      working-directory: ./Application-Backend
      run: ./mvnw test
