name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Adjust to your Java version
        distribution: 'temurin'

    - name: Build backend
      working-directory: ./Application-Backend
      run: ./mvnw clean install # Use mvn if you don't have the wrapper

    - name: Build frontend
      working-directory: ./Application-Frontend
      run: |
        npm install
        npm run build

    - name: Run backend tests
      working-directory: ./Application-Backend
      run: ./mvnw test
